apiVersion: v1
kind: Service
metadata:
  name: abc-technologies-service
spec:
  type: LoadBalancer
  selector:
    app: abc-technologies
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
